export enum screens {
  /* basic */
  splash = 'splash',
  home = 'home',
  dashboard = 'dashboard',
  /* auth */
  login = 'login',
  registration = 'registration',
  forgotPassword = 'forgotPassword',
  verifyOtp = 'verifyOtp',
  registrationEmail = 'registration-email',
  onboarding = 'onboarding',
  /* profile-setup */
  profileSetupOnboarding = 'profile-setup-onboarding',
  findAbout = 'find-about',
  dataPrivacy = 'data-privacy',
  selectDateOfBirth = 'select-date-of-birth',
  selectGender = 'select-gender',
  aboutCareer = 'about-career',
  shareInterests = 'share-interests',
  showStyle = 'show-style',
  /* events */
  events = 'events',
  friends = 'friends',
  profile = 'profile',
  messaging = 'messaging',
  /* verification */
  verification = 'verification',
  /* chats */
  eachConversation = 'each-conversation',
  /* profile */
  setting = 'setting',
  publicProfile = 'public-profile',
  myProfile = 'my-profile',
  editProfile = 'edit-profile',
  notification = 'notification',
  /* events */
  eventDetails = 'event-details',
  createEvent = 'create-event',
}
