export enum placeholders {
  enterEmail = 'Enter email',
  noData = 'No data found !!!',
  default = 'Enter Here',
  emailAddress = 'Email Address',
  password = 'Password',
  search = 'Search here...',
  search2 = 'Search',
  noOptions = 'No option available',
  writeSms = 'Write SMS',
  email = 'Email',
  noteMessage = 'Enter here... (For mentions use @)',
  noCustomFields = 'No Custom field available !',
  messageDeleted = 'This message is deleted',
  cantReply = "You can't reply to this conversation",
  contactBlocked = 'Contact was blocked/unsubscribed',
  appointmentURL = 'Write your appointment URL',
  typing = 'Type here',
  noNameFound = 'No Name',
  enterNumber = 'Enter Number',
  noConversation = 'No conversation found !',
  writeHere = 'Write Here...',
  subject = 'Subject',
  titleForQR = 'Enter title for quick reply',
  haveAttachment = 'You have attachments',
  noSenderSelected = 'No Sender Selected',
  selectTags = 'Select Tags',
}
